### ISSUE TITLE
Modintの入出力についての提案

### ISSUE THREAD

**Issue by Rogi52** [YNUCPC/ynu-icpc-library#42]
```cpp
friend ostream &operator<<(ostream &os, const mint &p) { return os << p.v; }
friend istream &operator>>(istream &is, mint &p) {
    int64_t t;
    is >> t;
    p = mint(t);
    return (is);
}
```
このように入出力演算を定義するのはどうでしょうか？

**Comment by Rogi52** [comment]
- メリット
  - 入出力関係の実装が簡潔になり、バグが減る
- デメリット
  - 今は `val()` でアクセスしており、`Modint`を利用していることに注意が向く。このメリットがなくなる
  - 実装量が増える

**Comment by noss3885** [comment]
現在は一応 modint.tex の方にグローバルに入出力ストリームを定義する形を載せているのですが、クラス内で定義できるのであれば、コードが分散せずによいと思います 👍

**Comment by noss3885** [comment]
私のほうで実装してみます
