### ISSUE TITLE
UndoつきUnion-Find木の追加

### ISSUE THREAD

**Issue by noss3885** [YNUCPC/ynu-icpc-library#53]
Undo(直前の操作を取り消す)が可能なUnion-Find木。

## 計算量

- find : O(log N)
- unite : O(log N)
- undo : O(1)

## 参考資料

- https://ei1333.github.io/library/structure/union-find/union-find-undo.cpp ([Unlicense](https://github.com/ei1333/library/blob/master/LICENSE))
- https://nyaannyaan.github.io/library/data-structure/rollback-union-find.hpp.html ([CC0-1.0](https://github.com/NyaanNyaan/library/blob/master/LICENSE))

## テスト問題

- [Persistent UnionFind - Library Checker](https://judge.yosupo.jp/problem/persistent_unionfind)
  - 更新履歴が木構造になっていることを考えると木を下るときunite, 上るときundoすると解ける

**Comment by Rogi52** [comment]
実装します。

**Comment by Rogi52** [comment]
実装について相談なのですが、以下の機能を加えますか？
* same(u,v): find(u) == find(v) を返す
* getsize(v): vを含む連結成分の頂点数を返す
* snapshot: 状態を保存
* rollback: 保存した状態まで undo

**Comment by noss3885** [comment]
- same() よく使うのであるといいと思います
- size(v) よく使うのであるといいと思います
- snapshot(),rollback() そんなに実装かからないのであればあっても良いと思います

**Comment by Rogi52** [comment]
ありがとうございます！
全て実装しようと思います。
